.PHONY: clean All

All:
	@echo "----------Building project:[ OperatorOverloading3 - Debug ]----------"
	@cd "OperatorOverloading" && "$(MAKE)" -f  "OperatorOverloading3.mk"
clean:
	@echo "----------Cleaning project:[ OperatorOverloading3 - Debug ]----------"
	@cd "OperatorOverloading" && "$(MAKE)" -f  "OperatorOverloading3.mk" clean
